name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frosthaven_assistant
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
      - run: flutter --version
      - name: Install xmllint
        run: sudo apt-get install -y ninja-build
      - run: flutter build linux
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux/x64/release/bundle